
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Random ;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hello
 */
public class studentuniversityinformation extends javax.swing.JFrame {

    /**
     * Creates new form studentuniversityinformation
     */
    public studentuniversityinformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departmentlapel = new javax.swing.JLabel();
        departmentcheckbox = new javax.swing.JComboBox<>();
        studentlevellapel = new javax.swing.JLabel();
        levelcombobox = new javax.swing.JComboBox<>();
        nooffinlapel = new javax.swing.JLabel();
        nooffinfield = new javax.swing.JTextField();
        noofcurlapel = new javax.swing.JLabel();
        noofcurfield1 = new javax.swing.JTextField();
        maxhouslkapel = new javax.swing.JLabel();
        maxhourfield = new javax.swing.JTextField();
        curhourslapel = new javax.swing.JLabel();
        curhouslkapel1 = new javax.swing.JLabel();
        showcurrenthours = new javax.swing.JLabel();
        showremainhours = new javax.swing.JLabel();
        calchoursbutton = new javax.swing.JButton();
        finishedhourslapel = new javax.swing.JLabel();
        showfinishedthours = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        showregestlabel = new javax.swing.JLabel();
        regestlabel = new javax.swing.JLabel();
        facultcombo = new javax.swing.JComboBox<>();
        enrollcomboo = new javax.swing.JComboBox<>();
        savebutton = new javax.swing.JButton();
        fullname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        departmentlapel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        departmentlapel.setText("Student's department information");

        departmentcheckbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departmentcheckbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department", "General", "Credit" }));
        departmentcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentcheckboxActionPerformed(evt);
            }
        });

        studentlevellapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentlevellapel.setText("Student's Level ");

        levelcombobox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        levelcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level & SEM", "Level 1 (SEM 1)", "Level 1 (SEM 2)", "Level 2 (SEM 3)", "Level 2 (SEM 4)", "Level 3 (SEM 5)", "Level 3 (SEM 6)", "Level 4 (SEM 7)", "Level 4 (SEM 8)" }));
        levelcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelcomboboxActionPerformed(evt);
            }
        });

        nooffinlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nooffinlapel.setText("Number of finshed courses");

        nooffinfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nooffinfieldActionPerformed(evt);
            }
        });

        noofcurlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noofcurlapel.setText("Number of current courses");

        noofcurfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofcurfield1ActionPerformed(evt);
            }
        });

        maxhouslkapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maxhouslkapel.setText("Maximum hours");

        maxhourfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxhourfieldActionPerformed(evt);
            }
        });

        curhourslapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curhourslapel.setText("Currnet hours");

        curhouslkapel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curhouslkapel1.setText("Remaining hours");

        showcurrenthours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showcurrenthours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showcurrenthoursKeyPressed(evt);
            }
        });

        showremainhours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showremainhours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showremainhoursKeyPressed(evt);
            }
        });

        calchoursbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calchoursbutton.setText("Calculate");
        calchoursbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calchoursbuttonActionPerformed(evt);
            }
        });

        finishedhourslapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        finishedhourslapel.setText("Finished hours");

        showfinishedthours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showfinishedthours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showfinishedthoursKeyPressed(evt);
            }
        });

        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        showregestlabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        regestlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regestlabel.setText("Regestration number");

        facultcombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        facultcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty", "Computers and data science", "Engineering", "Science", "Medcine", "Fine arts" }));

        enrollcomboo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enrollcomboo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enrollment year", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015" }));
        enrollcomboo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollcombooActionPerformed(evt);
            }
        });

        savebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        fullname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(enrollcomboo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentcheckbox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(facultcombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(studentlevellapel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(levelcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regestlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showregestlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(finishedhourslapel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(showfinishedthours, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(curhouslkapel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(showremainhours, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(curhourslapel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(showcurrenthours, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(maxhouslkapel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maxhourfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(noofcurlapel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(noofcurfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(calchoursbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nooffinlapel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nooffinfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(departmentlapel)
                            .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enrollcomboo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(facultcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentlevellapel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nooffinlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nooffinfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noofcurlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noofcurfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxhourfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxhouslkapel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calchoursbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finishedhourslapel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showfinishedthours, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curhourslapel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showcurrenthours, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(curhouslkapel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showremainhours, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regestlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showregestlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backbutton)
                            .addComponent(savebutton))
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentcheckboxActionPerformed

    private void nooffinfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nooffinfieldActionPerformed
           String finishedcourses = nooffinfield.getText();
    }//GEN-LAST:event_nooffinfieldActionPerformed

    private void noofcurfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofcurfield1ActionPerformed
        String currentcourses = noofcurfield1.getText();
    }//GEN-LAST:event_noofcurfield1ActionPerformed

    private void maxhourfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxhourfieldActionPerformed
        String maxhours = maxhourfield.getText();
    }//GEN-LAST:event_maxhourfieldActionPerformed

    private void showcurrenthoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showcurrenthoursKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_showcurrenthoursKeyPressed

    private void showremainhoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showremainhoursKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_showremainhoursKeyPressed

    private void calchoursbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calchoursbuttonActionPerformed
      
            String term = (String) levelcombobox.getSelectedItem() ;
            char term2 = term.charAt(13);
            String term3 =String.valueOf(term2);
         String facultycode=null ;
         String departmentcode= null ;
          
          if(facultcombo.getSelectedItem() == "Computers and data science"){
          facultycode ="25" ;
          }
          if(facultcombo.getSelectedItem() == "Engineering"){
          facultycode ="24" ;
          }
          if(facultcombo.getSelectedItem() == "Science"){
          facultycode ="23" ;
          }
          if(facultcombo.getSelectedItem() == "Fine arts"){
          facultycode ="22" ;
          }
          if(facultcombo.getSelectedItem() == "Medcine"){
          facultycode ="21" ;
          }
        if( departmentcheckbox.getSelectedItem()=="General"){
        departmentcode = "01";
        }
         if( departmentcheckbox.getSelectedItem()=="Credit"){
        departmentcode = "02";
    }
         
         Random r = new Random() ;
         int rno =(int) (Math.random()*10000);
      String Rno =  String.valueOf(rno) ;
      showregestlabel.setText(enrollcomboo.getSelectedItem()+term3+facultycode +departmentcode+Rno);
      
      
      
        String currentcourses = noofcurfield1.getText();
        int currentcourses2  = Integer.parseInt(currentcourses);
             
               String finishedcourses = nooffinfield.getText();
               int finishedcourses2  = Integer.parseInt(finishedcourses);
               
                    String maxhours = maxhourfield.getText();
                    int maxhours2  = Integer.parseInt(maxhours);
               
               
         showfinishedthours.setText(String.valueOf(finishedcourses2*3));
         showcurrenthours.setText(String.valueOf((currentcourses2)*3));
         
          showremainhours.setText(String.valueOf( maxhours2 -  (finishedcourses2*3 + currentcourses2*3) ));
        
          
          
          

    }//GEN-LAST:event_calchoursbuttonActionPerformed

    private void showfinishedthoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showfinishedthoursKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_showfinishedthoursKeyPressed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed

        studentinformation SI = new studentinformation();
        SI.show();
        dispose();

    }//GEN-LAST:event_backbuttonActionPerformed

    private void enrollcombooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollcombooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollcombooActionPerformed

    private void levelcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelcomboboxActionPerformed

    }//GEN-LAST:event_levelcomboboxActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        try {
            PrintWriter w = new PrintWriter(fullname.getText() +"(UniversityInfo)"+ ".txt" );
                        w.println("Student's Enrollment year : " + enrollcomboo.getSelectedItem());
                        w.println("Student's Faculty : " + facultcombo.getSelectedItem());
                        w.println("Student's Department : " + departmentcheckbox.getSelectedItem());
                        w.println("Student's  Level and Sem : " + levelcombobox.getSelectedItem());
                        w.println("Number of finished courses : " + nooffinfield.getText());
                        w.println("Number of current courses : " + noofcurfield1.getText());
                        w.println("maximum hours : " + maxhourfield.getText());
                        w.println("Number of finished hours : " + showfinishedthours.getText());
                        w.println("Number of current hours : " + showcurrenthours.getText());
                        w.println("Number of remaining hours : " + showremainhours.getText());
                        w.println("Student's regestration number : " + regestlabel.getText());






        } catch (FileNotFoundException ex) {
            Logger.getLogger(studentuniversityinformation.class.getName()).log(Level.SEVERE, null, ex);
        }
                 

                JOptionPane.showMessageDialog(null, "Draft Saved Successfully");
                

    }//GEN-LAST:event_savebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentuniversityinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentuniversityinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentuniversityinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentuniversityinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentuniversityinformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton calchoursbutton;
    private javax.swing.JLabel curhourslapel;
    private javax.swing.JLabel curhouslkapel1;
    private javax.swing.JComboBox<String> departmentcheckbox;
    private javax.swing.JLabel departmentlapel;
    private javax.swing.JComboBox<String> enrollcomboo;
    private javax.swing.JComboBox<String> facultcombo;
    private javax.swing.JLabel finishedhourslapel;
    public javax.swing.JLabel fullname;
    private javax.swing.JComboBox<String> levelcombobox;
    private javax.swing.JTextField maxhourfield;
    private javax.swing.JLabel maxhouslkapel;
    private javax.swing.JTextField noofcurfield1;
    private javax.swing.JLabel noofcurlapel;
    private javax.swing.JTextField nooffinfield;
    private javax.swing.JLabel nooffinlapel;
    private javax.swing.JLabel regestlabel;
    public javax.swing.JButton savebutton;
    private javax.swing.JLabel showcurrenthours;
    private javax.swing.JLabel showfinishedthours;
    private javax.swing.JLabel showregestlabel;
    private javax.swing.JLabel showremainhours;
    private javax.swing.JLabel studentlevellapel;
    // End of variables declaration//GEN-END:variables
}
