

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hello
 */
public class studentinformation extends javax.swing.JFrame {

    
    public studentinformation() {
        initComponents();
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        searchpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        informationwindow = new javax.swing.JPanel();
        firstnamelapel = new javax.swing.JLabel();
        secondnamelapel = new javax.swing.JLabel();
        thirdnameLabel = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        secondnamefield = new javax.swing.JTextField();
        thirdnamefield = new javax.swing.JTextField();
        datelapel = new javax.swing.JLabel();
        daycombobox = new javax.swing.JComboBox<>();
        monthcombobox = new javax.swing.JComboBox<>();
        yearcombox = new javax.swing.JComboBox<>();
        genderlapel = new javax.swing.JLabel();
        gendercheckbox = new javax.swing.JComboBox<>();
        nationalitylapel = new javax.swing.JLabel();
        nationalityfield = new javax.swing.JTextField();
        idtypelapel = new javax.swing.JLabel();
        nationalitytype = new javax.swing.JComboBox<>();
        nationalityID = new javax.swing.JTextField();
        flatelapel = new javax.swing.JLabel();
        studentregistrationlapel = new javax.swing.JLabel();
        studenthomelapel = new javax.swing.JLabel();
        houselapel = new javax.swing.JLabel();
        streetlapel = new javax.swing.JLabel();
        arealapel = new javax.swing.JLabel();
        citylapel = new javax.swing.JLabel();
        goverlapel = new javax.swing.JLabel();
        countrylapel = new javax.swing.JLabel();
        postallapel = new javax.swing.JLabel();
        flatefield = new javax.swing.JTextField();
        housefield = new javax.swing.JTextField();
        streetfield = new javax.swing.JTextField();
        areafield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        govfield = new javax.swing.JTextField();
        countryfield = new javax.swing.JTextField();
        postalfield = new javax.swing.JTextField();
        studentcontactlapel = new javax.swing.JLabel();
        emaillapel = new javax.swing.JLabel();
        emailtextfield = new javax.swing.JTextField();
        phonelapel = new javax.swing.JLabel();
        homephonelapel = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        homephonefield = new javax.swing.JTextField();
        nextbutton = new javax.swing.JButton();
        paymentinformationlabel = new javax.swing.JLabel();
        typeoffundingcheckbox = new javax.swing.JComboBox<>();
        noofpayfield = new javax.swing.JTextField();
        noodpaylapel = new javax.swing.JLabel();
        totalpaylapel = new javax.swing.JLabel();
        totalpayfield = new javax.swing.JTextField();
        egplapel = new javax.swing.JLabel();
        Amountpaidlapel = new javax.swing.JLabel();
        amountpaidfield = new javax.swing.JTextField();
        egplapel1 = new javax.swing.JLabel();
        transactionnumberlapel = new javax.swing.JLabel();
        transactionnumberfield = new javax.swing.JTextField();
        banklapel = new javax.swing.JLabel();
        bankfield = new javax.swing.JTextField();
        daytransactioncombo = new javax.swing.JComboBox<>();
        monthtransactioncombo = new javax.swing.JComboBox<>();
        yeartransactioncombo = new javax.swing.JComboBox<>();
        transactiondatelapel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student ID");

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchpanelLayout = new javax.swing.GroupLayout(searchpanel);
        searchpanel.setLayout(searchpanelLayout);
        searchpanelLayout.setHorizontalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(717, Short.MAX_VALUE))
        );
        searchpanelLayout.setVerticalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idfield, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        firstnamelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstnamelapel.setText("First Name : ");

        secondnamelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        secondnamelapel.setText("Middle Name : ");

        thirdnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thirdnameLabel.setText("Last Name : ");

        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });

        secondnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondnamefieldActionPerformed(evt);
            }
        });

        thirdnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdnamefieldActionPerformed(evt);
            }
        });

        datelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datelapel.setText("Date of Birth : ");

        daycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yearcombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        genderlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderlapel.setText("Gender : ");

        gendercheckbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Femal" }));

        nationalitylapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nationalitylapel.setText("Nationality : ");

        idtypelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idtypelapel.setText("Nationality ID : ");

        nationalitytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "National ID", "Passport", "Drive License" }));

        flatelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flatelapel.setText("Flat Number : ");

        studentregistrationlapel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentregistrationlapel.setText("Student's personal Information ");

        studenthomelapel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studenthomelapel.setText("Student's Home Address ");

        houselapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        houselapel.setText("House Number : ");

        streetlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        streetlapel.setText("Street Name : ");

        arealapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arealapel.setText("Area / District  : ");

        citylapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        citylapel.setText("City : ");

        goverlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        goverlapel.setText("Governorate Name : ");

        countrylapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countrylapel.setText("Country : ");

        postallapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        postallapel.setText("Postal Code : ");

        studentcontactlapel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentcontactlapel.setText("Student's  Contact Information ");

        emaillapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emaillapel.setText("Email adderss : ");

        phonelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phonelapel.setText("Student Phone number : ");

        homephonelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homephonelapel.setText("Student Home Phone number : ");

        homephonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homephonefieldActionPerformed(evt);
            }
        });

        nextbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextbutton.setText("Next");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });

        paymentinformationlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paymentinformationlabel.setText("Student's payment Information");

        typeoffundingcheckbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        typeoffundingcheckbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type of funding", "Self-funding", "Grant-funding" }));

        noofpayfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        noofpayfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofpayfieldActionPerformed(evt);
            }
        });

        noodpaylapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noodpaylapel.setText("Number of payments done");

        totalpaylapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalpaylapel.setText("Total amount payment");

        totalpayfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpayfieldActionPerformed(evt);
            }
        });

        egplapel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        egplapel.setText("EGP");

        Amountpaidlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Amountpaidlapel.setText("Amount paid ");

        amountpaidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidfieldActionPerformed(evt);
            }
        });

        egplapel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        egplapel1.setText("EGP");

        transactionnumberlapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transactionnumberlapel.setText("Transaction number");

        transactionnumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionnumberfieldActionPerformed(evt);
            }
        });

        banklapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        banklapel.setText("Bank of transaction ");

        bankfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankfieldActionPerformed(evt);
            }
        });

        daytransactioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthtransactioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yeartransactioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        transactiondatelapel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transactiondatelapel.setText("Data of transaction ");

        javax.swing.GroupLayout informationwindowLayout = new javax.swing.GroupLayout(informationwindow);
        informationwindow.setLayout(informationwindowLayout);
        informationwindowLayout.setHorizontalGroup(
            informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationwindowLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studenthomelapel)
                            .addComponent(studentregistrationlapel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addComponent(studentcontactlapel)
                        .addContainerGap(316, Short.MAX_VALUE))
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(citylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(informationwindowLayout.createSequentialGroup()
                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(idtypelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nationalitylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(datelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(secondnamelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstnamelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(thirdnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(informationwindowLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(daycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(monthcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(6, 6, 6)
                                                        .addComponent(yearcombox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(gendercheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(firstnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                        .addComponent(secondnamefield)
                                                        .addComponent(thirdnamefield))))
                                            .addGroup(informationwindowLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nationalityID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(nationalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(nationalitytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(flatelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(houselapel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(streetlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(arealapel)
                                            .addComponent(countrylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(housefield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(flatefield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(streetfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(areafield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(postalfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(informationwindowLayout.createSequentialGroup()
                                            .addComponent(goverlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(govfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                        .addGap(286, 286, 286)
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                                                .addComponent(emaillapel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(129, 129, 129))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(homephonelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(phonelapel))
                                                .addGap(26, 26, 26)))
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(homephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(typeoffundingcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(paymentinformationlabel))
                                                .addGap(149, 149, 149))
                                            .addGroup(informationwindowLayout.createSequentialGroup()
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(transactionnumberlapel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(transactionnumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(totalpaylapel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(totalpayfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(noodpaylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(noofpayfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(Amountpaidlapel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(amountpaidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(banklapel)
                                                            .addComponent(transactiondatelapel))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                                                                .addComponent(daytransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(monthtransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(bankfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(egplapel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(egplapel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(informationwindowLayout.createSequentialGroup()
                                                        .addComponent(yeartransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addComponent(postallapel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        informationwindowLayout.setVerticalGroup(
            informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationwindowLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentregistrationlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentcontactlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnamelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondnamelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thirdnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearcombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationwindowLayout.createSequentialGroup()
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gendercheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homephonelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalitylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalitytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idtypelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationalityID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(paymentinformationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studenthomelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeoffundingcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noodpaylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noofpayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(egplapel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalpayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalpaylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(egplapel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountpaidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amountpaidlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transactionnumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transactionnumberlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(banklapel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(informationwindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countrylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flatelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(houselapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(housefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arealapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citylapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goverlapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(govfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(informationwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daytransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthtransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeartransactioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextbutton)
                            .addComponent(postallapel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transactiondatelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(250, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informationwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(searchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informationwindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed

        String firstname = firstnamefield.getText() ; 
        
    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void homephonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homephonefieldActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_homephonefieldActionPerformed
      
      
       
    private void secondnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondnamefieldActionPerformed
        String secondname = secondnamefield.getText() ;
    }//GEN-LAST:event_secondnamefieldActionPerformed

    private void thirdnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdnamefieldActionPerformed
        String lastname = thirdnamefield.getText() ;
    }//GEN-LAST:event_thirdnamefieldActionPerformed

    private void noofpayfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofpayfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofpayfieldActionPerformed

    private void totalpayfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpayfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpayfieldActionPerformed

    private void amountpaidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountpaidfieldActionPerformed

    private void transactionnumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionnumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionnumberfieldActionPerformed

    private void bankfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankfieldActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        
        studentuniversityinformation SUI = new studentuniversityinformation() ; 
        SUI.show();
        dispose();
       
         try {
            PrintWriter w = new PrintWriter(firstnamefield.getText() +" "+ secondnamefield.getText() +" "+thirdnamefield.getText() + ".txt" );
            w.println("Student's Name : "+firstnamefield.getText()+" "+ secondnamefield.getText()+" "+ thirdnamefield.getText());
            w.println("Student's Birth Date : "+daycombobox.getSelectedItem()+"/"+ monthcombobox.getSelectedItem()+"/"+ yearcombox.getSelectedItem());
            w.println("Student's Gender : " + gendercheckbox.getSelectedItem());
            w.println("Student's Nationality : "+nationalityfield.getText() + "  "+ "Natinality Type : " +nationalitytype.getSelectedItem());
            w.println("Student's Nationality ID : " +nationalityID.getText() );
            w.println("Student's Address : " +countryfield.getText()+", "+cityfield.getText()+", "+areafield.getText());
            w.println("Student's Home Address : "+streetfield.getText()+", "+housefield.getText()+", "+flatefield.getText());
            w.println("Student's Governorate and his/her postal code : "+goverlapel.getText()+", "+postalfield.getText());
            w.println("Student's Email : "+ emaillapel.getText());
            w.println("Student's Number : "+ phonefield.getText());
            w.println("Student's Home number : "+ homephonefield.getText());
            w.println("Student's Type of funding : "+ typeoffundingcheckbox.getSelectedItem());
            w.println("Student's Payment done : "+ noofpayfield.getText());
            w.println("Student's Total Payment done : "+ totalpayfield.getText()+ "EGP");
            w.println("Student's Amount Paid : "+ amountpaidfield.getText()+ "EGP");
            w.println("Transaction Number : "+ transactionnumberfield.getText());
            w.println("Bank Name : "+ bankfield.getText());
            w.println("Student's Date of transaction : "+daytransactioncombo.getSelectedItem()+"/"+ monthtransactioncombo.getSelectedItem()+"/"+ yeartransactioncombo.getSelectedItem());

            w.close();
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        studentuniversityinformation SUI1 =new studentuniversityinformation();
        SUI1.fullname.setText(firstnamefield.getText()+" "+secondnamefield.getText()+" "+thirdnamefield.getText());
        SUI1.setVisible(true);
    }//GEN-LAST:event_nextbuttonActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amountpaidlapel;
    private javax.swing.JTextField amountpaidfield;
    private javax.swing.JTextField areafield;
    private javax.swing.JLabel arealapel;
    private javax.swing.JPanel background;
    private javax.swing.JTextField bankfield;
    private javax.swing.JLabel banklapel;
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel citylapel;
    private javax.swing.JTextField countryfield;
    private javax.swing.JLabel countrylapel;
    private javax.swing.JLabel datelapel;
    private javax.swing.JComboBox<String> daycombobox;
    private javax.swing.JComboBox<String> daytransactioncombo;
    private javax.swing.JLabel egplapel;
    private javax.swing.JLabel egplapel1;
    private javax.swing.JLabel emaillapel;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel firstnamelapel;
    private javax.swing.JTextField flatefield;
    private javax.swing.JLabel flatelapel;
    private javax.swing.JComboBox<String> gendercheckbox;
    private javax.swing.JLabel genderlapel;
    private javax.swing.JLabel goverlapel;
    private javax.swing.JTextField govfield;
    private javax.swing.JTextField homephonefield;
    private javax.swing.JLabel homephonelapel;
    private javax.swing.JTextField housefield;
    private javax.swing.JLabel houselapel;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel idtypelapel;
    private javax.swing.JPanel informationwindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> monthcombobox;
    private javax.swing.JComboBox<String> monthtransactioncombo;
    private javax.swing.JTextField nationalityID;
    private javax.swing.JTextField nationalityfield;
    private javax.swing.JLabel nationalitylapel;
    private javax.swing.JComboBox<String> nationalitytype;
    private javax.swing.JButton nextbutton;
    private javax.swing.JLabel noodpaylapel;
    private javax.swing.JTextField noofpayfield;
    private javax.swing.JLabel paymentinformationlabel;
    private javax.swing.JTextField phonefield;
    private javax.swing.JLabel phonelapel;
    private javax.swing.JTextField postalfield;
    private javax.swing.JLabel postallapel;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JTextField secondnamefield;
    private javax.swing.JLabel secondnamelapel;
    private javax.swing.JTextField streetfield;
    private javax.swing.JLabel streetlapel;
    private javax.swing.JLabel studentcontactlapel;
    private javax.swing.JLabel studenthomelapel;
    private javax.swing.JLabel studentregistrationlapel;
    private javax.swing.JLabel thirdnameLabel;
    private javax.swing.JTextField thirdnamefield;
    private javax.swing.JTextField totalpayfield;
    private javax.swing.JLabel totalpaylapel;
    private javax.swing.JLabel transactiondatelapel;
    private javax.swing.JTextField transactionnumberfield;
    private javax.swing.JLabel transactionnumberlapel;
    private javax.swing.JComboBox<String> typeoffundingcheckbox;
    private javax.swing.JComboBox<String> yearcombox;
    private javax.swing.JComboBox<String> yeartransactioncombo;
    // End of variables declaration//GEN-END:variables
}
